import mongoose from 'mongoose';
import { connectDB } from '../config/db';
import { User } from '../models/User';
import { Category } from '../models/Category';
import { Product } from '../models/Product';
import { Order } from '../models/Order';
import { HomepageContent } from '../models/HomepageContent';
import { StoreSettings } from '../models/StoreSettings';
import { ENV } from '../config/env';

const seedDatabase = async () => {
  try {
    console.log('[Seed] Connecting to database...');
    await connectDB();

    console.log('[Seed] Clearing existing collections...');
    await Promise.all([
      User.deleteMany({}),
      Category.deleteMany({}),
      Product.deleteMany({}),
      Order.deleteMany({}),
      HomepageContent.deleteMany({}),
      StoreSettings.deleteMany({}),
    ]);

    console.log('[Seed] Creating admin account...');
    const admin = await User.create({
      name: 'Hahndorf Store Manager',
      email: ENV.ADMIN_EMAIL,
      password: ENV.ADMIN_PASSWORD,
      role: 'admin',
    });
    console.log(`[Seed] Admin created: ${admin.email} (Password: ${ENV.ADMIN_PASSWORD})`);

    console.log('[Seed] Creating categories...');
    const categoriesData = [
      {
        name: 'Home-made Fudge',
        slug: 'home-made-fudge',
        description: 'Our signature copper-pan boiled artisan fudges crafted fresh in over 40 decadent flavours.',
        image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop',
        sortOrder: 1,
        status: 'active',
      },
      {
        name: 'Gift Boxes & Hampers',
        slug: 'gift-boxes-hampers',
        description: 'Curated tasting assortments in elegant presentation packaging, ready for any celebration.',
        image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800&auto=format&fit=crop',
        sortOrder: 2,
        status: 'active',
      },
      {
        name: 'Giant Freckles & Treats',
        slug: 'giant-freckles-treats',
        description: 'Iconic Australian giant milk and dark chocolate freckles covered in crunchy sprinkles.',
        image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?q=80&w=800&auto=format&fit=crop',
        sortOrder: 3,
        status: 'active',
      },
      {
        name: 'Belgian Chocolates',
        slug: 'belgian-chocolates',
        description: 'Rich hand-dipped chocolates, clusters, and gourmet bars created with Belgian couverture.',
        image: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=800&auto=format&fit=crop',
        sortOrder: 4,
        status: 'active',
      },
      {
        name: 'Artisan Ice Cream',
        slug: 'ice-cream',
        description: 'Churned on-site using rich Adelaide Hills cream and natural flavours (in-store experience).',
        image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?q=80&w=800&auto=format&fit=crop',
        sortOrder: 5,
        status: 'active',
      },
      {
        name: 'Reduced Sugar Confectionery',
        slug: 'reduced-sugar',
        description: 'Thoughtfully formulated treats allowing guilt-free indulgence without sacrificing flavour.',
        image: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?q=80&w=800&auto=format&fit=crop',
        sortOrder: 6,
        status: 'active',
      },
    ];

    const createdCategories = await Category.insertMany(categoriesData);
    const catMap = new Map<string, any>();
    createdCategories.forEach((cat) => catMap.set(cat.slug, cat._id));

    console.log('[Seed] Creating artisan products...');
    const fudgeCat = catMap.get('home-made-fudge');
    const giftCat = catMap.get('gift-boxes-hampers');
    const freckleCat = catMap.get('giant-freckles-treats');
    const chocCat = catMap.get('belgian-chocolates');
    const sugarCat = catMap.get('reduced-sugar');

    const productsData = [
      {
        name: 'Maple & Roasted Nut Fudge',
        slug: 'maple-and-nut-fudge',
        description: 'Velvety caramelised Canadian maple fudge packed with oven-roasted Australian walnuts and pecans. Hand-poured and cut in small batches.',
        category: fudgeCat,
        price: 6.50,
        weight: '110g Slice',
        stock: 35,
        sku: 'FSH-MAPLE-01',
        ingredients: 'Sugar, Condensed Milk, Butter, Glucose Syrup, Pure Maple Syrup, Roasted Pecans, Roasted Walnuts, Natural Flavour.',
        allergens: 'Contains Milk, Tree Nuts (Walnuts, Pecans). May contain peanuts and gluten.',
        storageInstructions: 'Store in an airtight container in a cool pantry. Best enjoyed at room temperature.',
        images: ['https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: true,
        bestseller: true,
        sortOrder: 1,
      },
      {
        name: 'Biscoff & Clotted Cream Fudge',
        slug: 'biscoff-and-clotted-cream-fudge',
        description: 'Spiced Belgian speculoos cookie butter swirled through luxurious Cornish-style clotted cream fudge, topped with crunchy biscuit crumble.',
        category: fudgeCat,
        price: 6.50,
        weight: '115g Slice',
        stock: 42,
        sku: 'FSH-BISCOFF-02',
        ingredients: 'Sugar, Condensed Milk, Clotted Cream, Butter, Lotus Biscoff Spread (Wheat Flour, Sugar, Vegetable Oils, Cinnamon), Salt.',
        allergens: 'Contains Dairy, Wheat (Gluten), Soy. May contain tree nuts.',
        storageInstructions: 'Store in a cool dry place. Keep sealed for fresh crunch.',
        images: ['https://images.unsplash.com/photo-1579372786545-d24232daf58c?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: true,
        bestseller: true,
        sortOrder: 2,
      },
      {
        name: 'Traditional Clotted Cream Fudge',
        slug: 'clotted-cream-fudge',
        description: 'The timeless British favourite, elevated with South Australian dairy. Meltingly smooth, buttery, and delicately golden.',
        category: fudgeCat,
        price: 6.50,
        weight: '100g Slice',
        stock: 50,
        sku: 'FSH-CLOTTED-03',
        ingredients: 'Sugar, Condensed Milk, Clotted Cream (12%), Butter, Glucose, Pure Vanilla Bean Paste.',
        allergens: 'Contains Milk/Dairy. May contain traces of nuts.',
        storageInstructions: 'Store in a cool dry pantry. Room temperature brings out peak creaminess.',
        images: ['https://images.unsplash.com/photo-1582293041079-7814c2f12063?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: true,
        sortOrder: 3,
      },
      {
        name: 'Adelaide Hills Salted Caramel Fudge',
        slug: 'salted-caramel-fudge',
        description: 'Rich slow-cooked caramel fudge infused with flakes of Australian sea salt for the sublime sweet-savoury contrast.',
        category: fudgeCat,
        price: 6.50,
        weight: '110g Slice',
        stock: 60,
        sku: 'FSH-SCARAMEL-04',
        ingredients: 'Sugar, Condensed Milk, Butter, Dark Brown Sugar, Flaked Australian Sea Salt, Natural Caramel Aroma.',
        allergens: 'Contains Dairy. Free from artificial preservatives.',
        storageInstructions: 'Keep in a cool cupboard away from humidity and heat.',
        images: ['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: true,
        bestseller: true,
        sortOrder: 4,
      },
      {
        name: 'Lemon Myrtle & Roasted Macadamia Fudge',
        slug: 'lemon-myrtle-macadamia-fudge',
        description: 'A distinctly Australian creation combining indigenous citrusy lemon myrtle with toasted Australian macadamia nuts in creamy white fudge.',
        category: fudgeCat,
        price: 7.00,
        weight: '115g Slice',
        stock: 28,
        sku: 'FSH-LMYRTLE-05',
        ingredients: 'Sugar, Full Cream Milk, White Chocolate, Roasted Australian Macadamias, Wild Lemon Myrtle Extract.',
        allergens: 'Contains Milk, Macadamia Tree Nuts. May contain traces of other nuts.',
        storageInstructions: 'Store in cool ambient conditions.',
        images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: true,
        bestseller: false,
        sortOrder: 5,
      },
      {
        name: 'Belgian Dark Chocolate Chilli Fudge',
        slug: 'chilli-chocolate-fudge',
        description: '70% Belgian dark chocolate fudge with a warming hint of cayenne and birds-eye chilli that blooms softly on the palate.',
        category: fudgeCat,
        price: 6.50,
        weight: '100g Slice',
        stock: 22,
        sku: 'FSH-CHILLI-06',
        ingredients: 'Sugar, Condensed Milk, 70% Dark Belgian Cocoa Mass, Butter, Ground Chilli Pepper, Sea Salt.',
        allergens: 'Contains Dairy. May contain traces of nuts and soy lecithin.',
        storageInstructions: 'Keep cool and sealed.',
        images: ['https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 6,
      },
      {
        name: 'Baileys Irish Cream Swirl Fudge',
        slug: 'baileys-irish-cream-fudge',
        description: 'Infused with authentic Irish cream liqueur, marrying notes of whiskey, cocoa, and fresh cream in a gorgeous dual-toned fudge slab.',
        category: fudgeCat,
        price: 6.50,
        weight: '110g Slice',
        stock: 30,
        sku: 'FSH-BAILEYS-07',
        ingredients: 'Sugar, Condensed Milk, Butter, Baileys Irish Cream Liqueur Extract, Dutch Cocoa, Vanilla.',
        allergens: 'Contains Dairy. Non-alcoholic confectionery flavouring.',
        storageInstructions: 'Store cool and dry.',
        images: ['https://images.unsplash.com/photo-1606312619070-d48b4c652a52?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: true,
        bestseller: true,
        sortOrder: 7,
      },
      {
        name: 'White Chocolate Raspberry Ripple Fudge',
        slug: 'white-choc-raspberry-fudge',
        description: 'Silky creamy white chocolate fudge rippled with a tangy reduction of Adelaide Hills raspberries.',
        category: fudgeCat,
        price: 6.50,
        weight: '110g Slice',
        stock: 38,
        sku: 'FSH-RASP-08',
        ingredients: 'Sugar, Condensed Milk, White Chocolate Couverture, Fresh Raspberry Coulis, Citric Acid, Butter.',
        allergens: 'Contains Dairy, Soy.',
        storageInstructions: 'Store in an airtight container at room temperature.',
        images: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: true,
        bestseller: false,
        sortOrder: 8,
      },
      {
        name: 'Cappuccino & Dark Cocoa Fudge',
        slug: 'cappuccino-fudge',
        description: 'Brewed espresso fudge topped with a dusting of rich cocoa and a velvety sweet milk layer.',
        category: fudgeCat,
        price: 6.50,
        weight: '100g Slice',
        stock: 25,
        sku: 'FSH-CAPPUCCINO-09',
        ingredients: 'Sugar, Condensed Milk, Butter, Roasted Arabica Coffee Beans, Dark Dutch Cocoa Powder, Vanilla.',
        allergens: 'Contains Dairy. Mild naturally occurring caffeine.',
        storageInstructions: 'Store cool, sealed, and dry.',
        images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 9,
      },
      {
        name: 'Caramel Macadamia Crunch Fudge',
        slug: 'caramel-macadamia-fudge',
        description: 'Golden caramel base studded with whole South Australian roasted macadamia nuts.',
        category: fudgeCat,
        price: 7.00,
        weight: '115g Slice',
        stock: 32,
        sku: 'FSH-MACADAMIA-10',
        ingredients: 'Sugar, Condensed Milk, Butter, Golden Syrup, Toasted Macadamia Nuts, Natural Caramel Essence.',
        allergens: 'Contains Milk, Macadamia Nuts.',
        storageInstructions: 'Store in a cool dry pantry.',
        images: ['https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: true,
        sortOrder: 10,
      },
      {
        name: 'Cookies & Cream Oreo Delight Fudge',
        slug: 'cookies-and-cream-fudge',
        description: 'Generous pieces of chocolate cookies crushed into a sweet vanilla cream fudge base.',
        category: fudgeCat,
        price: 6.50,
        weight: '110g Slice',
        stock: 45,
        sku: 'FSH-COOKIES-11',
        ingredients: 'Sugar, Condensed Milk, Butter, Crushed Cocoa Cookies (Wheat Flour, Cocoa, Sugar, Canola Oil), Vanilla.',
        allergens: 'Contains Dairy, Wheat (Gluten), Soy.',
        storageInstructions: 'Keep airtight in cool temperatures.',
        images: ['https://images.unsplash.com/photo-1579372786545-d24232daf58c?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: true,
        sortOrder: 11,
      },
      {
        name: 'Choc Mint Crisp Fudge',
        slug: 'choc-mint-fudge',
        description: 'Cool natural peppermint green fudge layered over a rich dark chocolate foundation.',
        category: fudgeCat,
        price: 6.50,
        weight: '105g Slice',
        stock: 29,
        sku: 'FSH-CHOCMINT-12',
        ingredients: 'Sugar, Condensed Milk, Dark Chocolate, Butter, Pure Peppermint Oil, Natural Chlorophyll.',
        allergens: 'Contains Dairy. May contain traces of tree nuts.',
        storageInstructions: 'Store in a cool cupboard.',
        images: ['https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 12,
      },
      {
        name: 'Choc Orange Zest Fudge',
        slug: 'choc-orange-fudge',
        description: 'Rich dark chocolate fudge infused with cold-pressed orange oil and candied orange zest.',
        category: fudgeCat,
        price: 6.50,
        weight: '105g Slice',
        stock: 20,
        sku: 'FSH-ORANGE-13',
        ingredients: 'Sugar, Condensed Milk, Cocoa, Butter, Orange Oil, Candied Citrus Peel.',
        allergens: 'Contains Dairy.',
        storageInstructions: 'Store in cool ambient conditions.',
        images: ['https://images.unsplash.com/photo-1606312619070-d48b4c652a52?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 13,
      },
      {
        name: 'Peanut Butter Swirl Fudge',
        slug: 'choc-peanut-butter-fudge',
        description: 'Creamy Australian roasted peanut butter swirled with Dutch cocoa fudge for a rich nutty treat.',
        category: fudgeCat,
        price: 6.50,
        weight: '115g Slice',
        stock: 24,
        sku: 'FSH-PBUTTER-14',
        ingredients: 'Sugar, Condensed Milk, Roasted Peanuts, Butter, Cocoa, Sea Salt.',
        allergens: 'Contains Dairy, Peanuts. May contain other tree nuts.',
        storageInstructions: 'Store cool and dry.',
        images: ['https://images.unsplash.com/photo-1582293041079-7814c2f12063?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 14,
      },
      {
        name: 'Carnival Fairy Floss Fudge',
        slug: 'fairy-floss-fudge',
        description: 'A nostalgic carnival pink and pastel blue marbled fudge bursting with classic spun sugar sweetness.',
        category: fudgeCat,
        price: 6.50,
        weight: '100g Slice',
        stock: 30,
        sku: 'FSH-FAIRY-15',
        ingredients: 'Sugar, Condensed Milk, Butter, Glucose Syrup, Natural Strawberry & Blue Raspberry Essence, Food Colourings.',
        allergens: 'Contains Milk.',
        storageInstructions: 'Store in cool ambient conditions away from direct heat.',
        images: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 15,
      },
      {
        name: 'Zesty Lime Sorbet Fudge',
        slug: 'lime-sorbet-fudge',
        description: 'Refreshing and bright white chocolate fudge infused with Australian Tahitian lime zest.',
        category: fudgeCat,
        price: 6.50,
        weight: '100g Slice',
        stock: 18,
        sku: 'FSH-LIME-16',
        ingredients: 'Sugar, Full Cream Milk, White Cocoa Butter, Fresh Lime Juice Reduction, Lime Oil.',
        allergens: 'Contains Dairy.',
        storageInstructions: 'Store sealed and cool.',
        images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 16,
      },
      {
        name: 'Mango & Clotted Cream Fudge',
        slug: 'mango-cream-fudge',
        description: 'Sweet tropical Australian Kensington Pride mango puree folded into rich clotted cream.',
        category: fudgeCat,
        price: 6.50,
        weight: '110g Slice',
        stock: 22,
        sku: 'FSH-MANGO-17',
        ingredients: 'Sugar, Milk, Clotted Cream, Mango Puree, Citric Acid, Butter.',
        allergens: 'Contains Dairy.',
        storageInstructions: 'Store cool and dry.',
        images: ['https://images.unsplash.com/photo-1579372786545-d24232daf58c?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 17,
      },
      {
        name: 'Tia Maria Coffee Liqueur Fudge',
        slug: 'tia-maria-fudge',
        description: 'Jamaican coffee rum liqueur essence combined with dark roasted espresso and sweet cream.',
        category: fudgeCat,
        price: 6.50,
        weight: '105g Slice',
        stock: 19,
        sku: 'FSH-TIAMARIA-18',
        ingredients: 'Sugar, Condensed Milk, Butter, Coffee Liqueur Extract, Dutch Cocoa.',
        allergens: 'Contains Dairy. Non-alcoholic confectionery.',
        storageInstructions: 'Store in an airtight container.',
        images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 18,
      },
      {
        name: 'Banana Choc Chip Fudge',
        slug: 'banana-choc-chip-fudge',
        description: 'Real Cavendish banana flavour packed with Belgian dark chocolate micro-chips.',
        category: fudgeCat,
        price: 6.50,
        weight: '110g Slice',
        stock: 24,
        sku: 'FSH-BANANA-19',
        ingredients: 'Sugar, Condensed Milk, Butter, Banana Puree Extract, Dark Chocolate Drops.',
        allergens: 'Contains Dairy, Soy.',
        storageInstructions: 'Store cool and dry.',
        images: ['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 19,
      },
      {
        name: 'Celebration Birthday Cake Fudge',
        slug: 'birthday-cake-fudge',
        description: 'Vanilla sponge cake batter flavoured fudge loaded with rainbow candy sprinkles and white chocolate drizzle.',
        category: fudgeCat,
        price: 6.50,
        weight: '110g Slice',
        stock: 34,
        sku: 'FSH-BDAY-20',
        ingredients: 'Sugar, Condensed Milk, Butter, Cake Batter Essence, Rainbow Nonpareils.',
        allergens: 'Contains Dairy, Soy.',
        storageInstructions: 'Store in an airtight container at room temp.',
        images: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 20,
      },
      {
        name: 'Old Fashioned Butterscotch Fudge',
        slug: 'butterscotch-fudge',
        description: 'Dark Muscovado sugar and golden cultured butter caramelised gently for deep, authentic toffee notes.',
        category: fudgeCat,
        price: 6.50,
        weight: '100g Slice',
        stock: 40,
        sku: 'FSH-BSCOTCH-21',
        ingredients: 'Muscovado Sugar, Cultured Butter, Condensed Milk, Molasses, Sea Salt.',
        allergens: 'Contains Dairy.',
        storageInstructions: 'Store cool and dry.',
        images: ['https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: true,
        sortOrder: 21,
      },

      // Gift Boxes
      {
        name: 'Hahndorf Heritage 6-Piece Taster Box',
        slug: 'hahndorf-heritage-6-piece-taster-box',
        description: 'Our most popular gift selection featuring 6 signature artisan fudge slices: Salted Caramel, Biscoff, Maple Nut, Clotted Cream, Baileys, and Choc Macadamia in an embossed golden gift box.',
        category: giftCat,
        price: 36.00,
        compareAtPrice: 39.00,
        weight: '650g Box',
        stock: 25,
        sku: 'FSH-GIFT-6BOX',
        ingredients: 'Assorted artisan fudges. Full ingredient and allergen listing included in box booklet.',
        allergens: 'Contains Dairy, Tree Nuts, Wheat (Gluten), Soy.',
        storageInstructions: 'Store in a cool dry pantry. 6-month shelf life unopened.',
        images: [
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop',
        ],
        status: 'active',
        featured: true,
        bestseller: true,
        sortOrder: 1,
      },
      {
        name: 'The Confectioner’s Grand Adelaide Hills Hamper',
        slug: 'grand-adelaide-hills-hamper',
        description: 'The ultimate sweet experience. Includes 8 assorted fudge slices, a Giant Milk Chocolate Freckle, hand-dipped dark chocolate clusters, and butter toffee brittle in a bespoke wooden keepsake crate.',
        category: giftCat,
        price: 79.00,
        compareAtPrice: 88.00,
        weight: '1.2kg Hamper',
        stock: 15,
        sku: 'FSH-HAMPER-GRAND',
        ingredients: 'Assorted confectionery and chocolates. See individual product packs inside.',
        allergens: 'Contains Dairy, Tree Nuts, Peanuts, Wheat (Gluten), Soy.',
        storageInstructions: 'Store in a cool dry place.',
        images: [
          'https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=800&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800&auto=format&fit=crop',
        ],
        status: 'active',
        featured: true,
        bestseller: false,
        sortOrder: 2,
      },

      // Freckles & Treats
      {
        name: 'Giant Milk Chocolate Rainbow Freckle (150g)',
        slug: 'giant-milk-chocolate-rainbow-freckle',
        description: 'An Australian confectionery legend! A thick 15cm disc of creamy Australian milk chocolate smothered with crunchy multi-coloured rainbow nonpareils.',
        category: freckleCat,
        price: 8.50,
        weight: '150g Disc',
        stock: 50,
        sku: 'FSH-FRECKLE-MILK',
        ingredients: 'Sugar, Milk Solids, Cocoa Butter, Cocoa Mass, Soy Lecithin, Rainbow Sprinkles (Sugar, Tapioca Starch, Glazing Agent, Colours).',
        allergens: 'Contains Milk, Soy. May contain traces of tree nuts and peanuts.',
        storageInstructions: 'Keep in a cool dark pantry below 22°C.',
        images: ['https://images.unsplash.com/photo-1582293041079-7814c2f12063?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: true,
        bestseller: true,
        sortOrder: 1,
      },
      {
        name: 'Giant Belgian Dark Chocolate Freckle (150g)',
        slug: 'giant-dark-chocolate-freckle',
        description: 'For dark chocolate connoisseurs: 54% bittersweet Belgian chocolate disc adorned with crisp pastel sprinkles.',
        category: freckleCat,
        price: 8.50,
        weight: '150g Disc',
        stock: 35,
        sku: 'FSH-FRECKLE-DARK',
        ingredients: 'Cocoa Mass, Sugar, Cocoa Butter, Soy Lecithin, Rainbow Sprinkles.',
        allergens: 'Contains Soy. Manufactured on equipment that processes dairy and tree nuts.',
        storageInstructions: 'Store in cool dry conditions.',
        images: ['https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 2,
      },

      // Belgian Chocolates
      {
        name: 'Handcrafted Roasted Almond Clusters (Dark Chocolate)',
        slug: 'roasted-almond-clusters-dark',
        description: 'Golden roasted South Australian almonds smothered in rich 70% dark Belgian chocolate with a dusting of sea salt.',
        category: chocCat,
        price: 11.50,
        weight: '180g Bag',
        stock: 28,
        sku: 'FSH-CHOC-ALMOND',
        ingredients: 'Roasted Almonds (55%), Cocoa Mass, Sugar, Cocoa Butter, Emulsifier (Soy Lecithin), Murray River Salt.',
        allergens: 'Contains Tree Nuts (Almonds), Soy. May contain milk traces.',
        storageInstructions: 'Store in a cool dry cupboard.',
        images: ['https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 1,
      },

      // Reduced Sugar
      {
        name: 'Reduced Sugar Caramel Velvet Fudge',
        slug: 'reduced-sugar-caramel-fudge',
        description: 'Sweetened with natural plant stevia and maltitol, delivering the rich buttery caramel taste with 75% less sugar.',
        category: sugarCat,
        price: 7.50,
        weight: '100g Slice',
        stock: 20,
        sku: 'FSH-RSUGAR-CARAMEL',
        ingredients: 'Maltitol, Full Cream Milk, Butter, Inulin Fibre, Natural Stevia Extract, Sea Salt.',
        allergens: 'Contains Dairy. Excess consumption may have a laxative effect.',
        storageInstructions: 'Store sealed in cool dry conditions.',
        images: ['https://images.unsplash.com/photo-1606312619070-d48b4c652a52?q=80&w=800&auto=format&fit=crop'],
        status: 'active',
        featured: false,
        bestseller: false,
        sortOrder: 1,
      },
    ];

    const createdProducts = await Product.insertMany(productsData);
    console.log(`[Seed] Successfully inserted ${createdProducts.length} artisan products!`);

    console.log('[Seed] Setting up Homepage Content...');
    await HomepageContent.create({
      hero: {
        headline: 'Hand-made happiness, one delicious bite at a time.',
        subheadline:
          'Welcome to South Australia’s confectionery haven. For over 40 years, we have been kettle-cooking authentic fudge in the historic German village of Hahndorf. Taste over 40 glorious flavours.',
        heroImage: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=1600&auto=format&fit=crop',
        badgeText: 'Artisan Confectioners of the Adelaide Hills • Since 1980',
        primaryCtaText: 'Explore Our Flavours',
        primaryCtaLink: '/shop',
        secondaryCtaText: 'Plan Your Store Visit',
        secondaryCtaLink: '/visit-us',
      },
      announcement: {
        enabled: true,
        text: '🇦🇺 Free Express Australia Post Shipping on all orders over $75 | Handcrafted in Hahndorf SA',
        link: '/shipping',
      },
      featuredSectionTitle: 'Signature Small-Batch Fudges',
      featuredSectionSubtitle: 'Slow-stirred in traditional copper kettles using pure South Australian dairy and golden butter.',
      bestsellerSectionTitle: 'Hahndorf Village Favourites',
      bestsellerSectionSubtitle: 'The beloved recipes visitors travel through the Adelaide Hills to taste again and again.',
      storySection: {
        title: 'Our Sweet Village Story',
        subtitle: 'Four Decades of Artisan Confectionery',
        description1:
          'Located in the heart of historic Hahndorf—Australia’s oldest surviving German settlement—The Fudge Shop has been a beloved tradition for generations of families, locals, and travellers exploring South Australia.',
        description2:
          'Every slab of fudge is hand-stirred in small batches using rich Australian cream, pure butter, and natural flavourings. From classic Clotted Cream and Maple Pecan to contemporary favourites like Biscoff, we take immense pride in every single slice.',
        image: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?q=80&w=1200&auto=format&fit=crop',
        badge: 'Hahndorf Heritage Confectioner',
      },
      visitSection: {
        title: 'Visit Us in Hahndorf, South Australia',
        description:
          'Immerse yourself in the warm aroma of melting caramel, sample our famous fudge flavours, and treat yourself to our artisan ice cream right on Main Street.',
        address: 'Shop 4, 56 Mount Barker Rd (Main Rd), Hahndorf SA 5245',
        hours: 'Open 7 Days: 10:00 AM – 5:00 PM',
        image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop',
      },
    });

    console.log('[Seed] Setting up Store Settings...');
    await StoreSettings.create({
      storeName: 'The Fudge Shop Hahndorf',
      phone: '(08) 8388 7970',
      email: 'contact@fudgeshophahndorf.com.au',
      address: {
        shop: 'Shop 4',
        street: '56 Mount Barker Rd (Main Rd)',
        suburb: 'Hahndorf',
        state: 'SA',
        postcode: '5245',
        country: 'Australia',
      },
      openingHours: 'Monday to Sunday: 10:00 AM – 5:00 PM',
      standardShippingFee: 12.50,
      expressShippingFee: 16.50,
      freeShippingThreshold: 75.00,
      currency: 'AUD',
      taxRate: 0.10,
      abn: '78 123 456 789',
      orderPrefix: 'FSH-2026-',
    });

    console.log('[Seed] Generating initial demo orders for Admin analytics...');
    const demoOrders = [
      {
        orderNumber: 'FSH-2026-8921',
        customer: {
          firstName: 'Clara',
          lastName: 'Macleod',
          email: 'clara.macleod@adelaide.edu.au',
          phone: '0412 345 678',
        },
        shippingAddress: {
          address: '42 King William St',
          city: 'Adelaide',
          state: 'SA',
          postcode: '5000',
          country: 'Australia',
        },
        items: [
          {
            product: createdProducts[0]._id,
            name: createdProducts[0].name,
            sku: createdProducts[0].sku,
            price: createdProducts[0].price,
            quantity: 2,
            subtotal: createdProducts[0].price * 2,
            image: createdProducts[0].images[0],
            weight: createdProducts[0].weight,
          },
          {
            product: createdProducts[1]._id,
            name: createdProducts[1].name,
            sku: createdProducts[1].sku,
            price: createdProducts[1].price,
            quantity: 2,
            subtotal: createdProducts[1].price * 2,
            image: createdProducts[1].images[0],
            weight: createdProducts[1].weight,
          },
          {
            product: createdProducts[21]._id, // 6-pack gift box
            name: createdProducts[21].name,
            sku: createdProducts[21].sku,
            price: createdProducts[21].price,
            quantity: 1,
            subtotal: createdProducts[21].price,
            image: createdProducts[21].images[0],
            weight: createdProducts[21].weight,
          },
        ],
        subtotal: 62.00,
        shippingAmount: 12.50,
        totalAmount: 74.50,
        paymentMethod: 'Credit Card (Visa)',
        paymentStatus: 'paid',
        orderStatus: 'Processing',
        notes: 'Please pack securely for a gift delivery.',
        timeline: [
          { status: 'Pending', note: 'Order placed online.', timestamp: new Date(Date.now() - 86400000) },
          { status: 'Confirmed', note: 'Payment verified and confirmed.', timestamp: new Date(Date.now() - 80000000) },
          { status: 'Processing', note: 'Box packed in Hahndorf kitchen.', timestamp: new Date(Date.now() - 40000000) },
        ],
      },
      {
        orderNumber: 'FSH-2026-8922',
        customer: {
          firstName: 'Oliver',
          lastName: 'Schmidt',
          email: 'oliver.schmidt@hills.net.au',
          phone: '0423 987 654',
        },
        shippingAddress: {
          address: '15 Onkaparinga Valley Rd',
          city: 'Balhannah',
          state: 'SA',
          postcode: '5242',
          country: 'Australia',
        },
        items: [
          {
            product: createdProducts[22]._id, // Grand hamper
            name: createdProducts[22].name,
            sku: createdProducts[22].sku,
            price: createdProducts[22].price,
            quantity: 1,
            subtotal: createdProducts[22].price,
            image: createdProducts[22].images[0],
            weight: createdProducts[22].weight,
          },
        ],
        subtotal: 79.00,
        shippingAmount: 0.00, // Free shipping over $75
        totalAmount: 79.00,
        paymentMethod: 'MasterCard',
        paymentStatus: 'paid',
        orderStatus: 'Delivered',
        notes: 'Leave at front porch if not home.',
        timeline: [
          { status: 'Pending', note: 'Order submitted.', timestamp: new Date(Date.now() - 172800000) },
          { status: 'Confirmed', note: 'Payment processed.', timestamp: new Date(Date.now() - 170000000) },
          { status: 'Processing', note: 'Hamper packaged.', timestamp: new Date(Date.now() - 150000000) },
          { status: 'Shipped', note: 'Dispatched via Australia Post Express.', timestamp: new Date(Date.now() - 100000000) },
          { status: 'Delivered', note: 'Parcel delivered to front porch.', timestamp: new Date(Date.now() - 20000000) },
        ],
      },
    ];

    await Order.insertMany(demoOrders);
    console.log('[Seed] Demo orders inserted successfully.');

    console.log('\n=============================================');
    console.log('🎉 SEEDING COMPLETE!');
    console.log(`Admin Login: ${ENV.ADMIN_EMAIL}`);
    console.log(`Admin Password: ${ENV.ADMIN_PASSWORD}`);
    console.log(`Artisan Products Seeded: ${createdProducts.length}`);
    console.log('=============================================\n');

    process.exit(0);
  } catch (error) {
    console.error('[Seed] Error during seeding:', error);
    process.exit(1);
  }
};

seedDatabase();
